version: '3.1'

services:

  db:
    image: hypriot/rpi-mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=wadb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

